#!/bin/bash

output_file="$1"
shift 1
input_files=("$@")
for f in "${input_files[@]}"; do echo "file '$f'" >>list.txt; done
ffmpeg -safe 0 -f concat -i list.txt -c copy "$(tr -s ' ' '_' <<<"$output_file")"
rm list.txt
